/**
 * @module
 *
 * This file contains the definitions for the seven diatonic modes, also known
 * as the church modes or Greek modes. These scales are fundamental to Western
 * music theory and are derived from the major scale.
 *
 * Each mode has a unique intervallic structure and a distinct emotional quality.
 * The modes are presented in their traditional order:
 * 1. Ionian (the major scale)
 * 2. Dorian
 * 3. Phrygian
 * 4. Lydian
 * 5. Mixolydian
 * 6. Aeolian (the natural minor scale)
 * 7. Locrian
 *
 * The `intervals` array for each mode includes the octave ("8"), which is
 * characteristic for scales and modes.
 */

import type {
  DiatonicModeKey,
  NoteSequenceTheme,
} from "../types/note-sequences.d.ts";

/**
 * A comprehensive record of the seven diatonic modes. Each mode is defined
 * as a `NoteSequenceTheme`, providing its names, intervals, type classifications,
 * and other musical properties.
 *
 * The keys of this record are `DiatonicModeKey`s, allowing for type-safe
 * access to each mode.
 *
 * @example
 * ```ts
 * import { diatonicModes } from "@musodojo/music-theory-data/note-sequences";
 *
 * const dorian = diatonicModes.dorian;
 * console.log(dorian.primaryName); // "Dorian"
 * console.log(dorian.intervals);   // ["1", "2", "♭3", "4", "5", "6", "♭7", "8"]
 * ```
 *
 * @see {@link NoteSequenceTheme} for the structure of each mode definition.
 * @see {@link DiatonicModeKey} for the available mode keys.
 */
export const diatonicModes: Record<DiatonicModeKey, NoteSequenceTheme> = {
  ionian: {
    primaryName: "Major",
    names: ["Major", "Ionian", "Major Scale", "Ionian Mode", "Diatonic Major"],
    intervals: ["1", "2", "3", "4", "5", "6", "7", "8"],
    integers: [0, 2, 4, 5, 7, 9, 11],
    type: [
      "major",
      "ionian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "first diatonic mode",
      "do mode",
    ],
    characteristics: [
      "bright",
      "happy",
      "stable",
      "uplifting",
      "consonant",
      "western",
      "foundational",
      "simple",
      "pop music",
      "major tonality",
      "commonly used western scale",
    ],
    pattern: ["whole", "whole", "half", "whole", "whole", "whole", "half"],
    patternShort: ["W", "W", "H", "W", "W", "W", "H"],
    exampleNotes: ["C", "D", "E", "F", "G", "A", "B", "C"],
    labelsOverride: {
      triad: new Map([
        [0, "M"],
        [2, "m"],
        [4, "m"],
        [5, "M"],
        [7, "M"],
        [9, "m"],
        [11, "o"],
      ]),
      romanTriad: new Map([
        [0, "I"],
        [2, "ii"],
        [4, "iii"],
        [5, "IV"],
        [7, "V"],
        [9, "vi"],
        [11, "viio"],
      ]),
      seventh: new Map([
        [0, "M7"],
        [2, "m7"],
        [4, "m7"],
        [5, "M7"],
        [7, "7"],
        [9, "m7"],
        [11, "ø7"],
      ]),
      romanSeventh: new Map([
        [0, "IM7"],
        [2, "iim7"],
        [4, "iiim7"],
        [5, "IVM7"],
        [7, "V7"],
        [9, "vim7"],
        [11, "viiø7"],
      ]),
    },
  },
  dorian: {
    primaryName: "Dorian",
    names: [
      "Dorian",
      "Minor ♮6",
      "Dorian Mode",
    ],
    intervals: ["1", "2", "♭3", "4", "5", "6", "♭7", "8"],
    integers: [0, 2, 3, 5, 7, 9, 10],
    type: [
      "minor",
      "dorian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "second diatonic mode",
      "re mode",
    ],
    characteristics: [
      "soulful",
      "funky",
      "jazzy",
      "hopeful",
      "celtic",
      "folk",
      "minor tonality",
      "versatile",
      "used in folk, jazz, and rock",
      "medieval",
      "minor feel with a hopeful twist",
    ],
    pattern: ["whole", "half", "whole", "whole", "whole", "half", "whole"],
    patternShort: ["W", "H", "W", "W", "W", "H", "W"],
    exampleNotes: ["D", "E", "F", "G", "A", "B", "C", "D"],
    labelsOverride: {
      triad: new Map([
        [0, "m"],
        [2, "m"],
        [3, "M"],
        [5, "M"],
        [7, "m"],
        [9, "o"],
        [10, "M"],
      ]),
      romanTriad: new Map([
        [0, "i"],
        [2, "ii"],
        [3, "III"],
        [5, "IV"],
        [7, "v"],
        [9, "vio"],
        [10, "VII"],
      ]),
      seventh: new Map([
        [0, "m7"],
        [2, "m7"],
        [3, "M7"],
        [5, "7"],
        [7, "m7"],
        [9, "ø7"],
        [10, "M7"],
      ]),
      romanSeventh: new Map([
        [0, "im7"],
        [2, "iim7"],
        [3, "IIIM7"],
        [5, "IV7"],
        [7, "vm7"],
        [9, "viø7"],
        [10, "VIIM7"],
      ]),
    },
  },
  phrygian: {
    primaryName: "Phrygian",
    names: [
      "Phrygian",
      "Minor ♭2",
      "Phrygian Mode",
    ],
    intervals: ["1", "♭2", "♭3", "4", "5", "♭6", "♭7", "8"],
    integers: [0, 1, 3, 5, 7, 8, 10],
    type: [
      "minor",
      "phrygian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "third diatonic mode",
      "mi mode",
    ],
    characteristics: [
      "exotic",
      "spanish",
      "flamenco",
      "tense",
      "dark",
      "dramatic",
      "minor tonality",
      "darker emotional tones",
      "often used in metal and flamenco",
    ],
    pattern: ["half", "whole", "whole", "whole", "half", "whole", "whole"],
    patternShort: ["H", "W", "W", "W", "H", "W", "W"],
    exampleNotes: ["E", "F", "G", "A", "B", "C", "D", "E"],
    labelsOverride: {
      triad: new Map([
        [0, "m"],
        [1, "M"],
        [3, "M"],
        [5, "m"],
        [7, "o"],
        [8, "M"],
        [10, "m"],
      ]),
      romanTriad: new Map([
        [0, "i"],
        [1, "II"],
        [3, "III"],
        [5, "iv"],
        [7, "vo"],
        [8, "VI"],
        [10, "vii"],
      ]),
      seventh: new Map([
        [0, "m7"],
        [1, "M7"],
        [3, "7"],
        [5, "m7"],
        [7, "ø7"],
        [8, "M7"],
        [10, "m7"],
      ]),
      romanSeventh: new Map([
        [0, "im7"],
        [1, "IIM7"],
        [3, "III7"],
        [5, "ivm7"],
        [7, "vø7"],
        [8, "VIM7"],
        [10, "viim7"],
      ]),
    },
  },
  lydian: {
    primaryName: "Lydian",
    names: ["Lydian", "Major ♯4", "Lydian Mode"],
    intervals: ["1", "2", "3", "♯4", "5", "6", "7", "8"],
    integers: [0, 2, 4, 6, 7, 9, 11],
    type: [
      "major",
      "lydian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "fourth diatonic mode",
      "fa mode",
    ],
    characteristics: [
      "dreamy",
      "floating",
      "ethereal",
      "cinematic",
      "bright",
      "bright major tonality",
      "used in film scores and jazz",
    ],
    pattern: ["whole", "whole", "whole", "half", "whole", "whole", "half"],
    patternShort: ["W", "W", "W", "H", "W", "W", "H"],
    exampleNotes: ["F", "G", "A", "B", "C", "D", "E", "F"],
    labelsOverride: {
      quality: new Map([[6, "A4"]]),
      relative: new Map([[6, "♯4"]]),
      extension: new Map([[6, "♯11"]]),
      triad: new Map([
        [0, "M"],
        [2, "M"],
        [4, "m"],
        [6, "o"],
        [7, "M"],
        [9, "m"],
        [11, "m"],
      ]),
      romanTriad: new Map([
        [0, "I"],
        [2, "II"],
        [4, "iii"],
        [6, "ivo"],
        [7, "V"],
        [9, "vi"],
        [11, "vii"],
      ]),
      seventh: new Map([
        [0, "M7"],
        [2, "7"],
        [4, "m7"],
        [6, "ø7"],
        [7, "M7"],
        [9, "m"],
        [11, "m7"],
      ]),
      romanSeventh: new Map([
        [0, "IM7"],
        [2, "II7"],
        [4, "iiim7"],
        [6, "ivø7"],
        [7, "VM7"],
        [9, "vim7"],
        [11, "viim7"],
      ]),
    },
  },
  mixolydian: {
    primaryName: "Mixolydian",
    names: [
      "Mixolydian",
      "Major ♭7",
      "Dominant Scale",
      "Mixolydian Mode",
    ],
    intervals: ["1", "2", "3", "4", "5", "6", "♭7", "8"],
    integers: [0, 2, 4, 5, 7, 9, 10],
    type: [
      "major",
      "dominant",
      "mixolydian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "fifth diatonic mode",
      "sol mode",
    ],
    characteristics: [
      "bluesy",
      "dominant",
      "funky",
      "rock",
      "energetic",
      "major tonality",
      "strong blues and rock feel",
    ],
    pattern: ["whole", "whole", "half", "whole", "whole", "half", "whole"],
    patternShort: ["W", "W", "H", "W", "W", "H", "W"],
    exampleNotes: ["G", "A", "B", "C", "D", "E", "F", "G"],
    labelsOverride: {
      triad: new Map([
        [0, "M"],
        [2, "m"],
        [4, "o"],
        [5, "M"],
        [7, "m"],
        [9, "m"],
        [10, "M"],
      ]),
      romanTriad: new Map([
        [0, "I"],
        [2, "ii"],
        [4, "iiio"],
        [5, "IV"],
        [7, "v"],
        [9, "vi"],
        [10, "VII"],
      ]),
      seventh: new Map([
        [0, "7"],
        [2, "m7"],
        [4, "ø7"],
        [5, "M7"],
        [7, "m7"],
        [9, "m7"],
        [10, "M7"],
      ]),
      romanSeventh: new Map([
        [0, "IM7"],
        [2, "iim7"],
        [4, "iiiø7"],
        [5, "IVM7"],
        [7, "vm7"],
        [9, "vim7"],
        [10, "VIIM7"],
      ]),
    },
  },
  aeolian: {
    primaryName: "Minor",
    names: [
      "Minor",
      "Aeolian",
      "Natural Minor Scale",
      "Aeolian Mode",
      "Descending Melodic Minor Scale",
    ],
    intervals: ["1", "2", "♭3", "4", "5", "♭6", "♭7", "8"],
    integers: [0, 2, 3, 5, 7, 8, 10],
    type: [
      "minor",
      "aeolian",
      "natural",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "sixth diatonic mode",
      "la mode",
    ],
    characteristics: [
      "melancholic",
      "sad",
      "somber",
      "introspective",
      "dark",
      "minor tonality",
      "the relative minor of the major scale",
    ],
    pattern: ["whole", "half", "whole", "whole", "half", "whole", "whole"],
    patternShort: ["W", "H", "W", "W", "H", "W", "W"],
    exampleNotes: ["A", "B", "C", "D", "E", "F", "G", "A"],
    labelsOverride: {
      triad: new Map([
        [0, "m"],
        [2, "o"],
        [3, "M"],
        [5, "m"],
        [7, "m"],
        [8, "M"],
        [10, "M"],
      ]),
      romanTriad: new Map([
        [0, "i"],
        [2, "iio"],
        [3, "III"],
        [5, "iv"],
        [7, "v"],
        [8, "VI"],
        [10, "VII"],
      ]),
      seventh: new Map([
        [0, "m7"],
        [2, "ø7"],
        [3, "M7"],
        [5, "m7"],
        [7, "m7"],
        [8, "M7"],
        [10, "7"],
      ]),
      romanSeventh: new Map([
        [0, "im7"],
        [2, "iiø7"],
        [3, "IIIM7"],
        [5, "ivm7"],
        [7, "vm7"],
        [8, "VIM7"],
        [10, "VII7"],
      ]),
    },
  },
  locrian: {
    primaryName: "Locrian",
    names: [
      "Locrian",
      "Minor ♭2 ♭5",
      "Locrian Mode",
    ],
    intervals: ["1", "♭2", "♭3", "4", "♭5", "♭6", "♭7", "8"],
    integers: [0, 1, 3, 5, 6, 8, 10],
    type: [
      "diminished",
      "locrian",
      "mode",
      "scale",
      "church mode",
      "diatonic mode",
      "heptatonic",
      "seventh diatonic mode",
      "ti mode",
    ],
    characteristics: [
      "unsettling",
      "tense",
      "dark",
      "unstable",
      "dissonant",
      "highly dissonant",
      "rarely used as a tonal center",
    ],
    pattern: ["half", "whole", "whole", "half", "whole", "whole", "whole"],
    patternShort: ["H", "W", "W", "H", "W", "W", "W"],
    exampleNotes: ["B", "C", "D", "E", "F", "G", "A", "B"],
    labelsOverride: {
      triad: new Map([
        [0, "o"],
        [1, "M"],
        [3, "m"],
        [5, "m"],
        [6, "M"],
        [8, "M"],
        [10, "m"],
      ]),
      romanTriad: new Map([
        [0, "io"],
        [1, "II"],
        [3, "iii"],
        [5, "iv"],
        [6, "V"],
        [8, "VI"],
        [10, "vii"],
      ]),
      seventh: new Map([
        [0, "ø7"],
        [1, "M7"],
        [3, "m7"],
        [5, "m7"],
        [6, "M7"],
        [8, "7"],
        [10, "m7"],
      ]),
      romanSeventh: new Map([
        [0, "iø7"],
        [1, "IIM7"],
        [3, "iiim7"],
        [5, "ivm7"],
        [6, "VM7"],
        [8, "VI7"],
        [10, "viim7"],
      ]),
    },
  },
} as const;
