import type { NoteSequenceTheme } from "../types/note-sequences.d.ts";

export const melodicMinorModes: Record<string, NoteSequenceTheme> = {
  melodicMinor: {
    primaryName: "Melodic Minor",
    names: [
      "Melodic Minor",
      "Jazz Minor",
      "Ascending Melodic Minor Scale",
      "Minor Ionian",
      "Ionian ♭3",
      "Ionian Flat Third",
      "Dorian Major 7",
      "Dorian Major Seventh",
    ],
    sequence: [0, 2, 3, 5, 7, 9, 11],
    type: ["melodic minor mode", "minor", "mode", "scale", "first mode"],
    characteristics: [
      "minor tonality",
      "minor scale start, major scale finish",
      "jazz and classical music",
      "classical: raised 6th and 7th degrees when ascending",
      "classical: natural minor / aeolian mode when descending",
      "jazz: raised 6th and 7th degrees in both directions",
      "used in jazz improvisation",
      "common in jazz and fusion genres",
      "can be used over minor chords",
    ],
    pattern: ["whole", "half", "whole", "whole", "whole", "whole", "half"],
    patternShort: ["W", "H", "W", "W", "W", "W", "H"],
    degrees: ["1", "2", "♭3", "4", "5", "6", "7", "8"],
    exampleNotes: ["A", "B", "C", "D", "E", "F♯", "G♯", "A"],
  },
  dorianFlat2: {
    primaryName: "Dorian ♭2",
    names: [
      "Dorian ♭2",
      "Dorian Flat Second",
      "Phrygian ♮6",
      "Phrygian Raised Sixth",
    ],
    sequence: [0, 1, 3, 5, 7, 9, 10],
    type: [
      "melodic minor mode",
      "dorian",
      "minor",
      "mode",
      "scale",
      "second mode",
    ],
    characteristics: [
      "minor tonality",
      "jazz and fusion genres",
      "used in jazz improvisation",
      "can be used over minor chords",
      "used in modal jazz compositions",
      "Assyrian music",
    ],
    pattern: ["half", "whole", "whole", "whole", "whole", "half", "whole"],
    patternShort: ["H", "W", "W", "W", "W", "H", "W"],
    degrees: ["1", "♭2", "♭3", "4", "5", "6", "♭7", "8"],
    exampleNotes: ["A", "B♭", "C", "D", "E", "F♯", "G", "A"],
  },
};
