import type { NoteSequenceTheme } from "../types/note-sequences.d.ts";

export type OtherSequenceKey = "chromatic";

export const otherSequences: Record<OtherSequenceKey, NoteSequenceTheme> = {
  chromatic: {
    primaryName: "Chromatic",
    names: ["Chromatic", "Twelve Tone Scale"],
    sequence: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    type: ["chromatic", "scale", "non diatonic"],
    characteristics: ["all twelve pitches in an octave", "no tonal center"],
    pattern: [
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
      "half",
    ],
    patternShort: ["H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    degrees: [
      "1",
      "♭2",
      "2",
      "♭3",
      "3",
      "4",
      "♭5",
      "5",
      "♭6",
      "6",
      "♭7",
      "7",
      "8",
    ],
    exampleNotes: [
      "C",
      "C♯",
      "D",
      "D♯",
      "E",
      "F",
      "F♯",
      "G",
      "G♯",
      "A",
      "A♯",
      "B",
      "C",
    ],
  },
  // wholeTone: {
  //   primaryName: "Whole Tone Scale",
  //   names: [
  //     "Whole Tone Scale",
  //     "Whole Tone",
  //     "Whole Tone Ascending",
  //     "Whole Tone Descending",
  //     "Whole Tone Ascending Scale",
  //     "Whole Tone Descending Scale",
  //   ],
  //   sequence: [0, 2, 4, 6, 8, 10],
  //   type: ["whole tone", "scale", "first mode"],
  //   characteristics: [
  //     "six pitches in an octave",
  //     "no tonal center",
  //     "used in impressionistic music",
  //     "creates a dreamy or ethereal sound",
  //     "often used in film scores",
  //     "associated with composers like Debussy and Ravel",
  //   ],
  //   pattern: ["whole", "whole", "whole", "whole", "whole"],
  //   patternShort: ["W", "W", "W", "W", "W"],
  //   degrees: ["1", "2", "3", "4", "5", "6", "7"],
  // },
};
